version: '3'
services:
  api:
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - HOST=localhost
    ports:
      - '1337:1337'
    volumes:
      - './admin:/usr/src/api/strapi-app'
    depends_on:
      - db
    restart: always
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - '27017:27017'
    volumes:
      - 'db-data:/data/db'
    restart: always
volumes:
  db-data: null
