version: "3"
services:
  frontend:
    image: nginx
    volumes:
      - ./poi/dist:/usr/share/nginx/html
    ports:
      - "2333:80"
    networks: 
      - proxy
    depends_on:
      - api
    labels:
      - traefik.backend=frontend
      - traefik.frontend.rule=Host:meme.yuyuko.me
      - traefik.docker.network=proxy
      - traefik.port=80
  api:
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
    ports:
      - "1337:1337"
    networks: 
      - proxy
    labels:
      - traefik.backend=api
      - traefik.frontend.rule=Host:api.yuyuko.me
      - traefik.docker.network=proxy
      - traefik.port=1337
    volumes:
      - "./admin:/usr/src/api/strapi-app"
    depends_on:
      - db
    restart: always
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - "27017:27017"
    networks: 
      - proxy
    volumes:
      - "db-data:/data/db"
    restart: always
volumes:
  db-data: null
networks: 
  proxy:
    external: 
      name: proxy_proxy
